# Generated by Django 2.2.5 on 2019-09-10 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0070_indicator_indicator_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolatable',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tolatable',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalresult',
            name='tola_table',
        ),
        migrations.RemoveField(
            model_name='historicalresult',
            name='update_count_tola_table',
        ),
        migrations.RemoveField(
            model_name='result',
            name='tola_table',
        ),
        migrations.RemoveField(
            model_name='result',
            name='update_count_tola_table',
        ),
        migrations.AlterField(
            model_name='datacollectionfrequency',
            name='numdays',
            field=models.PositiveIntegerField(default=0, verbose_name='Frequency in number of days'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='standard',
            field=models.BooleanField(default=False, verbose_name='Standard (TolaData Admins Only)'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='record_id',
            field=models.CharField(blank=True, max_length=765, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=' ', max_digits=20, verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='agreement',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='complete',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectComplete', verbose_name='Project Complete'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='date_collected',
            field=models.DateField(blank=True, help_text=' ', null=True, verbose_name='Date collected'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='evidence',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Documentation', verbose_name='Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='indicator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.Indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='periodic_target',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.PeriodicTarget', verbose_name='Periodic target'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_submitted_by', to='workflow.TolaUser', verbose_name='Approval submitted by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_indicator', to='workflow.TolaUser', verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline_na',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Not applicable'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='comments',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.DataCollectionFrequency', verbose_name='Frequency of Data Collection'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data Collection Method'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data issues'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data points'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='definition',
            field=models.TextField(blank=True, help_text=' ', null=True, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, 'Direction of change (not applicable)'), (2, 'Increase (+)'), (3, 'Decrease (-)')], default=1, help_text=' ', null=True, verbose_name='Direction of Change'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='disaggregation',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.DisaggregationType', verbose_name='Disaggregation'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='external_service_record',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExternalServiceRecord', verbose_name='External Service ID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Changes to Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_key',
            field=models.UUIDField(default=uuid.uuid4, help_text=' ', verbose_name='Indicator key'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.IndicatorType', verbose_name='Indicator type'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Information Use'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_cumulative',
            field=models.NullBooleanField(help_text=' ', verbose_name='C / NC'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Rationale or Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='key_performance_indicator',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Key Performance Indicator for this program?'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name='Life of Program (LoP) target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of Verification / Data Source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Method of Analysis'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(help_text=' ', max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='number',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='objectives',
            field=models.ManyToManyField(blank=True, help_text=' ', related_name='obj_indicator', to='indicators.Objective', verbose_name='Program Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='old_level',
            field=models.CharField(blank=True, help_text=' ', max_length=80, null=True, verbose_name='Old Level'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Quality Assurance Measures'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Rationale for target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingFrequency', verbose_name='Frequency of Reporting'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible Person(s) and Team'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='strategic_objectives',
            field=models.ManyToManyField(blank=True, help_text=' ', related_name='strat_indicator', to='indicators.StrategicObjective', verbose_name='Country Strategic Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency',
            field=models.IntegerField(choices=[(1, 'Life of Program (LoP) only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_custom',
            field=models.CharField(blank=True, help_text=' ', max_length=100, null=True, verbose_name='First event name'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_num_periods',
            field=models.IntegerField(blank=True, help_text=' ', null=True, verbose_name='Number of target periods*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_start',
            field=models.DateField(blank=True, help_text=' ', null=True, verbose_name='First target period begins*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=' ', max_length=135, null=True, verbose_name='Unit of measure'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure_type',
            field=models.IntegerField(choices=[(1, 'Number (#)'), (2, 'Percentage (%)')], default=1, help_text=' ', null=True, verbose_name='Unit Type'),
        ),
        migrations.AlterField(
            model_name='result',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=' ', max_digits=20, verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='result',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_agreement2', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='result',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_data', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='result',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='result',
            name='complete',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_complete2', to='workflow.ProjectComplete', verbose_name='Project Complete'),
        ),
        migrations.AlterField(
            model_name='result',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_collected',
            field=models.DateField(blank=True, help_text=' ', null=True, verbose_name='Date collected'),
        ),
        migrations.AlterField(
            model_name='result',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.DisaggregationValue', verbose_name='Disaggregation Value'),
        ),
        migrations.AlterField(
            model_name='result',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Documentation', verbose_name='Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='result',
            name='indicator',
            field=models.ForeignKey(help_text=' ', on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='result',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.PeriodicTarget', verbose_name='Periodic target'),
        ),
        migrations.AlterField(
            model_name='result',
            name='program',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i_program', to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='result',
            name='site',
            field=models.ManyToManyField(blank=True, help_text=' ', to='workflow.SiteProfile', verbose_name='Site'),
        ),
        migrations.DeleteModel(
            name='ReportingPeriod',
        ),
        migrations.DeleteModel(
            name='TolaTable',
        ),
    ]
