# Generated by Django 2.2.5 on 2019-10-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0071_auto_20190910_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresult',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='historicalresult',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='result',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='result',
            name='complete',
        ),
    ]
