# Generated by Django 2.2.5 on 2019-10-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0072_auto_20191001_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresult',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='result',
            name='evidence',
        ),
    ]
