# Generated by Django 2.2.5 on 2019-10-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0073_auto_20191003_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationtype',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
