# Generated by Django 2.2.5 on 2019-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0074_disaggregationtype_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationtype',
            name='selected_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
