# Generated by Django 2.2.5 on 2019-11-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0075_disaggregationtype_selected_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDisaggregation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('indicators.disaggregationtype',),
        ),
        migrations.CreateModel(
            name='GlobalDisaggregation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('indicators.disaggregationtype',),
        ),
        migrations.RemoveField(
            model_name='disaggregationtype',
            name='description',
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='disaggregation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationType', verbose_name='Disaggregation'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='disaggregation_type',
            field=models.CharField(blank=True, max_length=135, verbose_name='Disaggregation'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='standard',
            field=models.BooleanField(default=False, verbose_name='Global (all programs, all countries)'),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='disaggregation_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationLabel', verbose_name='Disaggregation category'),
        ),
    ]
