# Generated by Django 2.2.5 on 2019-11-07 20:30

from django.db import migrations, models

def initial_order(apps, schema_editor):
    DisaggregationType = apps.get_model("indicators", "DisaggregationType")
    for disaggregation in DisaggregationType.objects.all():
        for c, label in enumerate(
            disaggregation.disaggregationlabel_set.all().order_by(models.F('customsort').asc(nulls_last=True))
            ):
            if label.customsort != c+1:
                label.customsort = c+1
                label.save()

class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0076_auto_20191105_1414'),
    ]

    operations = [
        migrations.RunPython(initial_order),
        migrations.AlterModelOptions(
            name='disaggregationlabel',
            options={'ordering': ['customsort']},
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='customsort',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort order'),
        ),
    ]
