# Generated by Django 2.2.5 on 2019-11-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0078_auto_20191107_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationtype',
            name='disaggregation_type',
            field=models.CharField(max_length=135, verbose_name='Disaggregation'),
        ),
    ]
