# Generated by Django 2.2.5 on 2019-11-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0079_auto_20191107_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Rationale or justification for indicator'),
        ),
        migrations.CreateModel(
            name='DisaggregatedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationLabel', verbose_name='Disaggregation category')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.Result')),
            ],
        ),
        migrations.AddConstraint(
            model_name='disaggregatedvalue',
            constraint=models.UniqueConstraint(fields=('result', 'category'), name='unique_disaggregation_per_result'),
        ),
    ]
