# Generated by Django 2.2.5 on 2019-12-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0080_disaggregated_value_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='disaggregation_value',
        ),
        migrations.DeleteModel(
            name='DisaggregationValue',
        ),
    ]
