# Generated by Django 2.2.5 on 2019-12-26 22:48

from django.db import migrations



def non_reversible_migration(apps, schema_editor):
    """Operation to "reverse" an unreversible change"""
    pass


def remove_label(apps, schema_editor):
    DisaggregationType = apps.get_model('indicators', 'DisaggregationType')
    try:
        dt = DisaggregationType.objects.get(pk=109)
        label = dt.disaggregationlabel_set.filter(label='Agriculture')
        label.delete()
    except DisaggregationType.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0082_global_disaggregations_data_migration'),
    ]

    operations = [
        migrations.RunPython(remove_label, non_reversible_migration)
    ]
