# Generated by Django 2.2.12 on 2020-06-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0085_constrain_disaggs_to_avoid_dupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_method',
            field=models.TextField(blank=True, help_text=' ', max_length=2500, null=True, verbose_name='Data Collection Method'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=' ', max_length=1000, null=True, verbose_name='Data points'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='information_use',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Information Use'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='means_of_verification',
            field=models.TextField(blank=True, help_text=' ', max_length=1500, null=True, verbose_name='Means of Verification / Data Source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='method_of_analysis',
            field=models.TextField(blank=True, help_text=' ', max_length=4000, null=True, verbose_name='Method of Analysis'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_person',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Responsible Person(s) and Team'),
        ),
    ]
