# Generated by Django 2.2.12 on 2020-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0086_indicator_fieldlengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, 'Not applicable'), (2, 'Increase (+)'), (3, 'Decrease (-)')], default=1, help_text=' ', null=True, verbose_name='Direction of Change'),
        ),
    ]
