# Generated by Django 2.2.9 on 2020-10-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0087_auto_20200629_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='approval_submitted_by',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='approved_by',
        ),
    ]
