# Generated by Django 2.2.9 on 2020-11-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0089_copy_and_remove_notes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='comments',
            field=models.TextField(blank=True, help_text=' ', max_length=4000, null=True, verbose_name='Comments'),
        ),
    ]
