# Generated by Django 2.2.9 on 2020-10-06 21:07

from django.db import migrations

def copy_information_use_field_to_comments(apps, schema_editor):
    Indicator = apps.get_model("indicators", "Indicator")
    db_alias = schema_editor.connection.alias
    information_use_indicators = Indicator.objects.using(db_alias).filter(
        information_use__isnull=False).exclude(information_use='')
    for information_use_indicator in information_use_indicators:
        comments = information_use_indicator.comments
        new_comments = ''
        if comments:
            new_comments = comments + "\n\nInformation use / Utilisation de l’information / Uso de información: "
        new_comments += information_use_indicator.information_use
        information_use_indicator.comments = new_comments
        information_use_indicator.information_use = None
        information_use_indicator.save()

def copy_quality_assurance_field_to_comments(apps, schema_editor):
    Indicator = apps.get_model("indicators", "Indicator")
    db_alias = schema_editor.connection.alias
    quality_assurance_indicators = Indicator.objects.using(db_alias).filter(
        quality_assurance__isnull=False).exclude(quality_assurance='')
    for quality_assurance_indicator in quality_assurance_indicators:
        comments = quality_assurance_indicator.comments
        new_comments = ''
        if comments:
            new_comments = (comments + "\n\nQuality assurance measures / Mesures d’assurance qualité "
                            "/ Medidas de aseguramiento de la calidad: ")
        new_comments += quality_assurance_indicator.quality_assurance
        quality_assurance_indicator.comments = new_comments
        quality_assurance_indicator.quality_assurance = None
        quality_assurance_indicator.save()

def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0089_copy_and_remove_notes_field'),
    ]

    operations = [
        migrations.RunPython(copy_information_use_field_to_comments, reverse),
        migrations.RunPython(copy_quality_assurance_field_to_comments, reverse),
    ]
