# Generated by Django 2.2.14 on 2020-11-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0090_auto_20201110_1444'),
        ('indicators', '0090_auto_20201118_1121'),
    ]

    operations = [
    ]
