# Generated by Django 2.2.14 on 2021-03-22 14:29

from django.db import migrations


def copy_indicator_changes_field_to_comments(apps, schema_editor):
    Indicator = apps.get_model("indicators", "Indicator")
    db_alias = schema_editor.connection.alias
    filtered_indicators = Indicator.objects\
        .using(db_alias)\
        .filter(indicator_changes__isnull=False)\
        .exclude(indicator_changes='')
    for indicator in filtered_indicators:
        comments = indicator.comments
        new_comments = ''
        if comments:
            new_comments = comments + "\n\nChanges to indicator / Changements apportés à l’indicateur / Cambios en el indicador: "
        new_comments += indicator.indicator_changes
        indicator.comments = new_comments
        indicator.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0096_reporting_and_data_collection_updates'),
    ]

    operations = [
        migrations.RunPython(copy_indicator_changes_field_to_comments, reverse),
        migrations.RemoveField(
            model_name='indicator',
            name='indicator_changes',
        ),
    ]
