# Generated by Django 2.2.21 on 2021-05-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0058_add_region_to_country'),
        ('indicators', '0097_remove_indicator_indicator_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacollectionfrequency',
            options={'ordering': ['sort_order'], 'verbose_name': 'Data Collection Frequency'},
        ),
        migrations.AlterModelOptions(
            name='reportingfrequency',
            options={'ordering': ['sort_order'], 'verbose_name': 'Reporting Frequency'},
        ),
        migrations.CreateModel(
            name='BulkIndicatorImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('file_path', models.FilePathField(path='/indicators/bulk_import_files')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_indicator_import_files', to='workflow.Program')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_indicator_import_files', to='workflow.TolaUser')),
            ],
        ),
    ]
