# Generated by Django 2.2.21 on 2021-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0098_bulk_indicator_import_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkindicatorimportfile',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='bulkindicatorimportfile',
            name='uuid',
        ),
        migrations.AddField(
            model_name='bulkindicatorimportfile',
            name='file_name',
            field=models.CharField(default='a_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkindicatorimportfile',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'Indicator data'), (2, 'Error template')], default=1),
            preserve_default=False,
        ),
    ]
