# Generated by Django 2.2.21 on 2021-07-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0099_adjust_bulk_import_file_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text='Enter a numeric value for the baseline. If a baseline is not yet known or not applicable, enter a zero or select the &ldquo;Not applicable&rdquo; checkbox. The baseline can always be updated at a later point in time.', max_length=255, null=True, verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='number',
            field=models.CharField(blank=True, help_text='This number is displayed in place of the indicator number automatically generated through the results framework. An admin can turn on auto-numbering in program settings.', max_length=255, null=True, verbose_name='Number'),
        ),
    ]
