# Generated by Django 2.2.21 on 2021-07-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0100_add_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, help_text='Identify the source of this indicator (e.g. Mercy Corps DIG, EC, USAID, etc.) If the indicator is brand new and created specifically for the program, enter &ldquo;Custom&rdquo;.', max_length=255, null=True, verbose_name='Source'),
        ),
    ]
