# Generated by Django 2.2.21 on 2021-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0102_indicator_was_bulk_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text='Enter a numeric value for the baseline that is greater than or equal to zero. If a baseline is not yet known or not applicable, enter a zero or select the &ldquo;Not applicable&rdquo; checkbox. The baseline can always be updated at a later point in time.', max_length=255, null=True, verbose_name='Baseline'),
        ),
    ]
