# Generated by Django 2.2.21 on 2021-10-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0103_update_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='is_cumulative',
            field=models.IntegerField(help_text=' ', null=True, verbose_name='C / NC'),
        ),
    ]
