# Generated by Django 2.2.21 on 2021-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0104_nonsumming_cumulative'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='admin_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Participant count'), (1, 'Test/Demo')], null=True),
        ),
    ]
