# Generated by Django 2.2.21 on 2021-12-21 22:11

from django.db import migrations, models


def copy_standard_to_new_field(apps, schema_editor):
    DisaggregationType = apps.get_model("indicators", "DisaggregationType")
    db_alias = schema_editor.connection.alias
    for dt in DisaggregationType.objects.using(db_alias).all():
        dt.global_type = dt.standard
        dt.save()


def reverse_func(apps, schema_editor):
    DisaggregationType = apps.get_model("indicators", "DisaggregationType")
    db_alias = schema_editor.connection.alias
    for dt in DisaggregationType.objects.using(db_alias).all():
        dt.standard = dt.global_type
        dt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0105_indicator_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationtype',
            name='global_type',
            field=models.IntegerField(choices=[(0, 'Not global'), (1, 'Global (all countries and programs)'), (2, 'Global (participant count only)')], verbose_name='Global disaggregation'),
        ),
        migrations.RunPython(copy_standard_to_new_field, reverse_func),
        migrations.RemoveField(
            model_name='disaggregationtype',
            name='standard',
        ),

    ]



