# Generated by Django 2.2.21 on 2021-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0106_disaggregationtype_global_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationtype',
            name='global_type',
            field=models.IntegerField(choices=[(0, 'Not global'), (1, 'Global (all countries and programs)'), (2, 'Global (participant count only)')], default=0, verbose_name='Global disaggregation'),
        ),
    ]
