# Generated by Django 2.2.21 on 2021-12-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0107_add_global_type_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Outcome theme name')),
                ('is_active', models.BooleanField(verbose_name='Active?')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='outcome_themes',
            field=models.ManyToManyField(blank=True, null=True, to='indicators.OutcomeTheme'),
        ),
    ]
