# Generated by Django 2.2.21 on 2021-12-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0108_add_outcome_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='outcome_theme',
            field=models.ManyToManyField(blank=True, null=True, to='indicators.OutcomeTheme'),
        ),
    ]
