# Generated by Django 2.2.21 on 2022-01-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0108_add_outcome_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='outcome_themes',
            field=models.ManyToManyField(to='indicators.OutcomeTheme'),
        ),
    ]
