# Generated by Django 2.2.21 on 2022-01-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0109_outcomethemes_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='outcome_themes',
            field=models.ManyToManyField(blank=True, to='indicators.OutcomeTheme'),
        ),
    ]
