# Generated by Django 3.2.12 on 2022-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0110_outcome_theme_blank_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDAAOutcomeTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Outcome theme name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
    ]
