# Generated by Django 3.2.12 on 2022-08-12 13:13

from django.db import migrations


idaa_outcome_themes = [
    "Food Security",
    "Water Security",
    "Economic Opportunities",
    "Peace and Stability",
    "NA"
]


def populate_idaa_outcome_themes(apps, schema_editor):
    idaa_outcome_themes_model = apps.get_model('indicators', 'IDAAOutcomeTheme')

    for idaa_outcome_theme in idaa_outcome_themes:
        idaa_outcome_themes_model.objects.get_or_create(name=idaa_outcome_theme)


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0112_alter_idaaoutcometheme_options'),
    ]

    operations = [
        migrations.RunPython(populate_idaa_outcome_themes)
    ]
