# Generated by Django 3.2.12 on 2022-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0113_populate_idaaoutcomethemes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkindicatorimportfile',
            options={'verbose_name': 'Bulk Indicator Import File', 'verbose_name_plural': 'Bulk Indicator Import Files'},
        ),
        migrations.AlterModelOptions(
            name='countrydisaggregation',
            options={'verbose_name': 'Country Disaggregation', 'verbose_name_plural': 'Country Disaggregations'},
        ),
        migrations.AlterModelOptions(
            name='datacollectionfrequency',
            options={'ordering': ['sort_order'], 'verbose_name': 'Data Collection Frequency', 'verbose_name_plural': 'Data Collection Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='disaggregatedvalue',
            options={'verbose_name': 'Disaggregated Value', 'verbose_name_plural': 'Disaggregated Values'},
        ),
        migrations.AlterModelOptions(
            name='disaggregationlabel',
            options={'ordering': ['customsort'], 'verbose_name': 'Disaggregation Label', 'verbose_name_plural': 'Disaggregation Labels'},
        ),
        migrations.AlterModelOptions(
            name='disaggregationtype',
            options={'verbose_name': 'Disaggregation Type', 'verbose_name_plural': 'Disaggregation Types'},
        ),
        migrations.AlterModelOptions(
            name='externalservice',
            options={'verbose_name': 'External Service', 'verbose_name_plural': 'External Services'},
        ),
        migrations.AlterModelOptions(
            name='externalservicerecord',
            options={'verbose_name': 'External Service Record', 'verbose_name_plural': 'External Service Records'},
        ),
        migrations.AlterModelOptions(
            name='globaldisaggregation',
            options={'verbose_name': 'Global Disaggregation', 'verbose_name_plural': 'Global Disaggregations'},
        ),
        migrations.AlterModelOptions(
            name='historicalresult',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicator Result'},
        ),
        migrations.AlterModelOptions(
            name='idaaoutcometheme',
            options={'ordering': ('name',), 'verbose_name': 'IDAA Outcome Theme', 'verbose_name_plural': 'IDAA Outcome Themes'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('create_date',), 'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.AlterModelOptions(
            name='indicatortype',
            options={'verbose_name': 'Indicator Type', 'verbose_name_plural': 'Indicator Types'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('customsort',), 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='leveltier',
            options={'ordering': ('tier_depth',), 'verbose_name': 'Level Tier', 'verbose_name_plural': 'Level Tiers'},
        ),
        migrations.AlterModelOptions(
            name='leveltiertemplate',
            options={'verbose_name': 'Level Tier Templates', 'verbose_name_plural': 'Level Tier Templates'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('program', 'name'), 'verbose_name': 'Program Objective', 'verbose_name_plural': 'Program Objectives'},
        ),
        migrations.AlterModelOptions(
            name='outcometheme',
            options={'verbose_name': 'Outcome Theme', 'verbose_name_plural': 'Outcome Themes'},
        ),
        migrations.AlterModelOptions(
            name='periodictarget',
            options={'ordering': ('customsort', '-create_date'), 'verbose_name': 'Periodic Target', 'verbose_name_plural': 'Periodic Targets'},
        ),
        migrations.AlterModelOptions(
            name='pinnedreport',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Pinned Report', 'verbose_name_plural': 'Pinned Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportingfrequency',
            options={'ordering': ['sort_order'], 'verbose_name': 'Reporting Frequency', 'verbose_name_plural': 'Reporting Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('indicator', 'date_collected'), 'verbose_name': 'Indicator Result', 'verbose_name_plural': 'Indicator Results'},
        ),
        migrations.AlterModelOptions(
            name='strategicobjective',
            options={'ordering': ('country', 'name'), 'verbose_name': 'Country Strategic Objective', 'verbose_name_plural': 'Country Strategic Objectives'},
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='global_type',
            field=models.IntegerField(choices=[(0, 'Not global'), (1, 'Global (all countries and programs)'), (2, 'Global (participant count only)')], default=0, verbose_name='Global Disaggregation'),
        ),
        migrations.AlterField(
            model_name='idaaoutcometheme',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Outcome theme name'),
        ),
    ]
