ADMINS:
 -
   - "admin"
   - "toladata@example.org"

ALLOWED_HOSTS:
 - "example.org"

EMAIL_USE_TLS: True
EMAIL_HOST: 'smtp.gmail.com'
EMAIL_PORT: 587
EMAIL_HOST_USER: 'sys@example.org'
EMAIL_HOST_PASSWORD: 'XXXXXXXXXXXX'
DEFAULT_FROM_EMAIL: 'sys@example.org'
SERVER_EMAIL: "tola@example.org"
EMAIL_BACKEND: "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH: "/tmp/tola-messages"

# Uncomment DEV_APPS and DEV_MIDDLEWARE_AFTER if you want to enable silk profiling
# DEV_APPS:
#     - 'silk'
#
# DEV_MIDDLEWARE_AFTER:
#     - 'silk.middleware.SilkyMiddleware'

# SILK_ENABLED: True
# SILKY_PYTHON_PROFILER: True
# SILKY_PYTHON_PROFILER_BINARY: True


DATABASES:
 default:
   ENGINE: "django.db.backends.mysql"
   NAME: "DB_NAME"
   USER: "DB_USER"
   PASSWORD: "DB_PASSWORD"
   HOST: "localhost"
   PORT: ""
   OPTIONS:
       charset: "utf8mb4"
   TEST:
       CHARSET: "utf8mb4"
       COLLATION: "utf8mb4_unicode_ci"


########## GOOGLE AUTH
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "111111111111-aaaAAAAABBBBDDEE888SSSCCCCDDDDD9.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "XXXXXXXXXXXXXXXXXXXXXXXX"
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: "example.org"

CACHES:
 default:
   BACKEND: "django.core.cache.backends.locmem.LocMemCache"

AUTHENTICATION_BACKENDS:
 - 'social_core.backends.google.GoogleOAuth2'
 - 'social_core.backends.saml.SAMLAuth'
 - 'django.contrib.auth.backends.ModelBackend'

# If report server then limit navigation and allow access to public dashboards
REPORT_SERVER: False
OFFLINE_MODE: False
NON_LDAP: True

TEMPLATE_DEBUG: False
DEBUG: True

# Google Analytics Tracking code
GOOGLE_ANALYTICS_PROPERTY_ID: 'UA-1111111-11'
GOOGLE_ANALYTICS_DOMAIN: 'example.org'

SECRET_KEY: 'replace with a suitable key'

LOGFILE: '/path/to/log/file'

PROGRAM_API_BASE_URL: 'https://program.api/endpoint/'
PROGRAM_API_TOKEN: 'replace with a program API token'

SOCIAL_AUTH_SAML_SP_ENTITY_ID: None
SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: None
SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: None
SOCIAL_AUTH_SAML_ORG_INFO: None
SOCIAL_AUTH_SAML_TECHNICAL_CONTACT: None
SOCIAL_AUTH_SAML_SUPPORT_CONTACT: None
SOCIAL_AUTH_SAML_ENABLED_IDPS: None
