# Generated by Django 2.2.5 on 2019-10-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0002_auto_20190910_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='initiation',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='office_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='province',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='project_agreement',
        ),
    ]
