# Generated by Django 2.2.5 on 2019-10-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0003_auto_20191001_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='program',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='program',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='TrainingAttendance',
        ),
    ]
