# Generated by Django 2.2.5 on 2019-10-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0051_auto_20190910_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TolaSites',
        ),
    ]
