# Generated by Django 2.2.5 on 2019-10-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0053_auto_20191001_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
