# Generated by Django 2.2.5 on 2019-10-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0054_delete_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmarks',
            name='site',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Benchmarks',
        ),
    ]
