# Generated by Django 2.2.5 on 2019-10-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0055_auto_20191003_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalbudget',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='HistoricalBudget',
        ),
    ]
