# Generated by Django 2.2.5 on 2019-10-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0056_auto_20191003_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedUser',
        ),
    ]
