# Generated by Django 2.2.21 on 2021-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0058_add_region_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='external_program_id',
            field=models.IntegerField(null=True, verbose_name='External program id'),
        ),
    ]
