# Generated by Django 3.2.12 on 2022-04-20 19:25

from django.db import migrations, models
import django.db.models.deletion
import workflow.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0059_program_external_program_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='gaitid',
            new_name='legacy_gaitid',
        ),
        migrations.CreateModel(
            name='GaitID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaitid', models.IntegerField()),
                ('donor', models.TextField(null=True)),
                ('donor_dept', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaitid', to='workflow.program')),
            ],
            options={
                'unique_together': {('gaitid', 'program')},
            },
        ),
        migrations.CreateModel(
            name='FundCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.IntegerField(validators=[workflow.validators.validate_fund_code])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('gaitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.gaitid')),
            ],
            options={
                'unique_together': {('fund_code', 'gaitid')},
            },
        ),
    ]
