# Generated by Django 3.2.12 on 2022-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0111_idaaoutcometheme'),
        ('workflow', '0061_programdiscrepancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDAASector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector Name')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'ordering': ('sector',),
            },
        ),
        migrations.AddField(
            model_name='program',
            name='idaa_outcome_theme',
            field=models.ManyToManyField(blank=True, to='indicators.IDAAOutcomeTheme'),
        ),
        migrations.AddField(
            model_name='program',
            name='idaa_sector',
            field=models.ManyToManyField(blank=True, to='workflow.IDAASector', verbose_name='Sector'),
        ),
    ]
