# Generated by Django 3.2.12 on 2022-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0114_verbose_names'),
        ('workflow', '0063_populate_idaasector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fundcode',
            options={'verbose_name': 'Fund Code', 'verbose_name_plural': 'Fund Codes'},
        ),
        migrations.AlterModelOptions(
            name='gaitid',
            options={'verbose_name': 'GAIT ID', 'verbose_name_plural': 'GAIT IDs'},
        ),
        migrations.AlterModelOptions(
            name='historicalsiteprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Site Profile'},
        ),
        migrations.AlterModelOptions(
            name='idaasector',
            options={'ordering': ('sector',), 'verbose_name': 'IDAA Sector', 'verbose_name_plural': 'IDAA Sectors'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'ordering': ('profile',), 'verbose_name': 'Profile Type', 'verbose_name_plural': 'Profile Types'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('name',), 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='programaccess',
            options={'verbose_name': 'Program Access', 'verbose_name_plural': 'Program Access'},
        ),
        migrations.AlterModelOptions(
            name='programdiscrepancy',
            options={'verbose_name': 'Program Discrepancy', 'verbose_name_plural': 'Program Discrepancies'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('sector',), 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='siteprofile',
            options={'ordering': ('name',), 'verbose_name': 'Site Profile', 'verbose_name_plural': 'Site Profiles'},
        ),
        migrations.AlterModelOptions(
            name='tolauser',
            options={'ordering': ('name',), 'verbose_name': 'Tola User', 'verbose_name_plural': 'Tola Users'},
        ),
        migrations.AlterField(
            model_name='idaasector',
            name='sector',
            field=models.CharField(max_length=255, unique=True, verbose_name='Sector Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Program End Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='funding_status',
            field=models.CharField(max_length=255, verbose_name='Funding Status'),
        ),
        migrations.AlterField(
            model_name='program',
            name='idaa_outcome_theme',
            field=models.ManyToManyField(blank=True, to='indicators.IDAAOutcomeTheme', verbose_name='IDAA Outcome Theme'),
        ),
        migrations.AlterField(
            model_name='program',
            name='idaa_sector',
            field=models.ManyToManyField(blank=True, to='workflow.IDAASector', verbose_name='IDAA Sector'),
        ),
        migrations.AlterField(
            model_name='program',
            name='legacy_gaitid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legacy GAIT ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Program Start Date'),
        ),
    ]
