# Generated by Django 3.2.12 on 2022-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0064_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaitid',
            name='donor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gaitid',
            name='donor_dept',
            field=models.TextField(blank=True, null=True),
        ),
    ]
