ALTER DATABASE `tola_activity` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`activitydb_customdashboard` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`activitydb_documentationapp` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`activitydb_faq` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`activitydb_feedback` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`authtoken_token` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`auth_group` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`auth_group_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`auth_permission` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`auth_user` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`auth_user_groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`auth_user_user_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`djangocosign_country` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`djangocosign_office` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`djangocosign_region` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`djangocosign_userprofile` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`djangocosign_userprofile_countries` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`django_admin_log` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`django_content_type` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`django_migrations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`django_session` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`django_site` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`feed_googlecredentialsmodel` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary_distribution` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary_program` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary_training` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_collecteddata_community` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_collecteddata_sector` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_datacollectionfrequency` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_disaggregatedvalue` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_disaggregationlabel` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_disaggregationtype` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_externalservice` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_externalservicerecord` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_historicalresult` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_indicator` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_indicatortype` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_indicator_disaggregation` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_indicator_indicator_type` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_indicator_objectives` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_indicator_strategic_objectives` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_level` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_leveltier` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_leveltiertemplate` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_objective` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_periodictarget` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_pinnedreport` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_reportingfrequency` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_result` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_result_site` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`indicators_strategicobjective` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`readtoken_token` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`read_read` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`read_readtype` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`reports_report` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`report_builder_format` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`report_builder_report` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`report_builder_report_starred` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`silo_datafield` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`silo_silo` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`silo_valuestore` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`social_auth_association` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`social_auth_code` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`social_auth_nonce` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`social_auth_partial` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`social_auth_usersocialauth` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`tola_management_countryadminauditlog` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`tola_management_organizationadminauditlog` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`tola_management_programadminauditlog` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`tola_management_programauditlog` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`tola_management_usermanagementauditlog` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_country` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_landtype` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_organization` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_organization_sectors` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_profiletype` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_program` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_program_country` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_program_sector` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_program_user_access` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_quantitativeoutputs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_sector` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_tolauser` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`workflow_tolauser_countries` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `tola_activity`.`activitydb_customdashboard` CHANGE `dashboard_name` `dashboard_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`activitydb_documentationapp` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`activitydb_feedback` CHANGE `page` `page` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`activitydb_feedback` CHANGE `severity` `severity` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_group` CHANGE `name` `name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_permission` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_permission` CHANGE `codename` `codename` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_user` CHANGE `password` `password` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_user` CHANGE `username` `username` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_user` CHANGE `first_name` `first_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_user` CHANGE `last_name` `last_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`auth_user` CHANGE `email` `email` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`authtoken_token` CHANGE `key` `key` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_admin_log` CHANGE `object_repr` `object_repr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_content_type` CHANGE `app_label` `app_label` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_content_type` CHANGE `model` `model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_migrations` CHANGE `app` `app` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_migrations` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_session` CHANGE `session_key` `session_key` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_site` CHANGE `domain` `domain` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_site` CHANGE `name` `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`djangocosign_country` CHANGE `name` `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`djangocosign_country` CHANGE `iso_two_letters_code` `iso_two_letters_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`djangocosign_office` CHANGE `long_name` `long_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`djangocosign_office` CHANGE `name` `name` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`djangocosign_region` CHANGE `code` `code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`djangocosign_region` CHANGE `name` `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`djangocosign_userprofile` CHANGE `title` `title` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`djangocosign_userprofile` CHANGE `name` `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary` CHANGE `beneficiary_name` `beneficiary_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary` CHANGE `father_name` `father_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary` CHANGE `gender` `gender` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_beneficiary` CHANGE `remarks` `remarks` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `distribution_name` `distribution_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `distribution_indicator` `distribution_indicator` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `distribution_implementer` `distribution_implementer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `reporting_period` `reporting_period` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `distribution_location` `distribution_location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `input_type_distributed` `input_type_distributed` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `distributor_name_and_affiliation` `distributor_name_and_affiliation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `distributor_contact_number` `distributor_contact_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_filled_by` `form_filled_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_filled_by_position` `form_filled_by_position` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_filled_by_contact_num` `form_filled_by_contact_num` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_filled_date` `form_filled_date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_verified_by` `form_verified_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_verified_by_position` `form_verified_by_position` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_verified_by_contact_num` `form_verified_by_contact_num` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `form_verified_date` `form_verified_date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_distribution` CHANGE `total_received_input` `total_received_input` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `training_name` `training_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `implementer` `implementer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `reporting_period` `reporting_period` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `location` `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `community` `community` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `training_duration` `training_duration` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `start_date` `start_date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `end_date` `end_date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `trainer_name` `trainer_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `trainer_contact_num` `trainer_contact_num` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `form_filled_by` `form_filled_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`formlibrary_trainingattendance` CHANGE `form_filled_by_contact_num` `form_filled_by_contact_num` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_datacollectionfrequency` CHANGE `frequency` `frequency` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_datacollectionfrequency` CHANGE `description` `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_disaggregationlabel` CHANGE `label` `label` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_disaggregationtype` CHANGE `disaggregation_type` `disaggregation_type` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_externalservice` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_externalservice` CHANGE `url` `url` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_externalservice` CHANGE `feed_url` `feed_url` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_externalservicerecord` CHANGE `full_url` `full_url` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_externalservicerecord` CHANGE `record_id` `record_id` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_historicalresult` CHANGE `history_type` `history_type` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_historicalresult` CHANGE `history_change_reason` `history_change_reason` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_historicalresult` CHANGE `record_name` `record_name` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_historicalresult` CHANGE `evidence_url` `evidence_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `name` `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `number` `number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `source` `source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `baseline` `baseline` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `means_of_verification` `means_of_verification` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `data_collection_method` `data_collection_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `responsible_person` `responsible_person` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `method_of_analysis` `method_of_analysis` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `information_use` `information_use` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `unit_of_measure` `unit_of_measure` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `target_frequency_custom` `target_frequency_custom` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `old_level` `old_level` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `indicator_key` `indicator_key` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_indicatortype` CHANGE `indicator_type` `indicator_type` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_level` CHANGE `name` `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_leveltier` CHANGE `name` `name` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_leveltiertemplate` CHANGE `names` `names` varchar(490) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_objective` CHANGE `name` `name` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_periodictarget` CHANGE `period` `period` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_pinnedreport` CHANGE `name` `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_pinnedreport` CHANGE `report_type` `report_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_pinnedreport` CHANGE `query_string` `query_string` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_reportingfrequency` CHANGE `frequency` `frequency` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_reportingfrequency` CHANGE `description` `description` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_result` CHANGE `non_logframe_indicator` `non_logframe_indicator` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_result` CHANGE `record_name` `record_name` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_result` CHANGE `evidence_url` `evidence_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_strategicobjective` CHANGE `name` `name` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_strategicobjective` CHANGE `status` `status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`read_read` CHANGE `read_name` `read_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`read_read` CHANGE `read_url` `read_url` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`read_read` CHANGE `file_data` `file_data` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`read_readtype` CHANGE `read_type` `read_type` varchar(135) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`read_readtype` CHANGE `description` `description` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`readtoken_token` CHANGE `read_token` `read_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`readtoken_token` CHANGE `read_secret` `read_secret` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CHANGE `path` `path` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CHANGE `path_verbose` `path_verbose` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CHANGE `field` `field` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CHANGE `field_verbose` `field_verbose` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CHANGE `name` `name` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_displayfield` CHANGE `aggregate` `aggregate` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `path` `path` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `path_verbose` `path_verbose` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `field` `field` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `field_verbose` `field_verbose` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `filter_type` `filter_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `filter_value` `filter_value` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_filterfield` CHANGE `filter_value2` `filter_value2` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_format` CHANGE `name` `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_format` CHANGE `string` `string` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_report` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_report` CHANGE `slug` `slug` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_report` CHANGE `report_file` `report_file` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`reports_report` CHANGE `description` `description` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`silo_datafield` CHANGE `original_name` `original_name` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`silo_datafield` CHANGE `name` `name` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`silo_valuestore` CHANGE `char_store` `char_store` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`social_auth_association` CHANGE `server_url` `server_url` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_association` CHANGE `handle` `handle` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_association` CHANGE `secret` `secret` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_association` CHANGE `assoc_type` `assoc_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_code` CHANGE `email` `email` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_code` CHANGE `code` `code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_nonce` CHANGE `server_url` `server_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_nonce` CHANGE `salt` `salt` varchar(65) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_partial` CHANGE `token` `token` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_partial` CHANGE `backend` `backend` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_usersocialauth` CHANGE `provider` `provider` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_usersocialauth` CHANGE `uid` `uid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_countryadminauditlog` CHANGE `change_type` `change_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_organizationadminauditlog` CHANGE `change_type` `change_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_programadminauditlog` CHANGE `change_type` `change_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_programauditlog` CHANGE `change_type` `change_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_usermanagementauditlog` CHANGE `change_type` `change_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_country` CHANGE `country` `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_country` CHANGE `code` `code` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_country` CHANGE `latitude` `latitude` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_country` CHANGE `longitude` `longitude` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `contact_leader` `contact_leader` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `contact_number` `contact_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `num_members` `num_members` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `info_source` `info_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `animal_type` `animal_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `approval` `approval` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `history_type` `history_type` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_historicalsiteprofile` CHANGE `history_change_reason` `history_change_reason` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_landtype` CHANGE `classify_land` `classify_land` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `organization_url` `organization_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `mode_of_contact` `mode_of_contact` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `primary_address` `primary_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `primary_contact_email` `primary_contact_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `primary_contact_name` `primary_contact_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `primary_contact_phone` `primary_contact_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_profiletype` CHANGE `profile` `profile` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_program` CHANGE `gaitid` `gaitid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_program` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_program` CHANGE `funding_status` `funding_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_program` CHANGE `cost_center` `cost_center` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_program_user_access` CHANGE `role` `role` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_quantitativeoutputs` CHANGE `description` `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_sector` CHANGE `sector` `sector` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `name` `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `contact_leader` `contact_leader` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `head_of_institution` `head_of_institution` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `contact_number` `contact_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `num_members` `num_members` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `animal_type` `animal_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `info_source` `info_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_siteprofile` CHANGE `approval` `approval` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `title` `title` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `name` `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `tables_api_token` `tables_api_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `activity_api_token` `activity_api_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `language` `language` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `mode_of_address` `mode_of_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `mode_of_contact` `mode_of_contact` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser` CHANGE `phone_number` `phone_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_tolauser_countries` CHANGE `role` `role` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`activitydb_customdashboard` CHANGE `dashboard_description` `dashboard_description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`activitydb_documentationapp` CHANGE `documentation` `documentation` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`activitydb_faq` CHANGE `question` `question` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`activitydb_faq` CHANGE `answer` `answer` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`activitydb_feedback` CHANGE `note` `note` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_admin_log` CHANGE `object_id` `object_id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`django_admin_log` CHANGE `change_message` `change_message` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`django_session` CHANGE `session_data` `session_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`feed_googlecredentialsmodel` CHANGE `credential` `credential` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_historicalresult` CHANGE `comments` `comments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `definition` `definition` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `comments` `comments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `notes` `notes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `data_issues` `data_issues` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `data_points` `data_points` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `indicator_changes` `indicator_changes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `justification` `justification` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `quality_assurance` `quality_assurance` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicator` CHANGE `rationale_for_target` `rationale_for_target` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`indicators_indicatortype` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_level` CHANGE `assumptions` `assumptions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_objective` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_result` CHANGE `comments` `comments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`indicators_strategicobjective` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`read_read` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`report_builder_report` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`silo_silo` CHANGE `name` `name` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`silo_silo` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_partial` CHANGE `data` `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`social_auth_usersocialauth` CHANGE `extra_data` `extra_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_countryadminauditlog` CHANGE `previous_entry` `previous_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_countryadminauditlog` CHANGE `new_entry` `new_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_organizationadminauditlog` CHANGE `previous_entry` `previous_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_organizationadminauditlog` CHANGE `new_entry` `new_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_programadminauditlog` CHANGE `previous_entry` `previous_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_programadminauditlog` CHANGE `new_entry` `new_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_programauditlog` CHANGE `previous_entry` `previous_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`tola_management_programauditlog` CHANGE `new_entry` `new_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`tola_management_programauditlog` CHANGE `rationale` `rationale` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`tola_management_usermanagementauditlog` CHANGE `previous_entry` `previous_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`tola_management_usermanagementauditlog` CHANGE `new_entry` `new_entry` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_country` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `tola_activity`.`workflow_organization` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
ALTER TABLE `tola_activity`.`workflow_program` CHANGE `description` `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
