# Generated by Django 2.2.5 on 2019-09-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0008_programauditlog_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadminauditlog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='organizationadminauditlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='programadminauditlog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='programadminauditlog',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='+', to='indicators.Level'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='usermanagementauditlog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='usermanagementauditlog',
            name='modified_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.TolaUser'),
        ),
    ]
