# Generated by Django 2.2.9 on 2020-01-25 00:54

from django.db import migrations, models
import django.db.models.deletion
import tola_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0057_delete_loggeduser'),
        ('indicators', '0084_update_verbose_result_sites_name'),
        ('tola_management', '0009_auto_20190910_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadminauditlog',
            name='change_type',
            field=models.CharField(max_length=255, verbose_name='Modification type'),
        ),
        migrations.AlterField(
            model_name='organizationadminauditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='programadminauditlog',
            name='change_type',
            field=models.CharField(max_length=255, verbose_name='Modification type'),
        ),
        migrations.AlterField(
            model_name='programadminauditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='change_type',
            field=models.CharField(max_length=255, verbose_name='Modification type'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='usermanagementauditlog',
            name='change_type',
            field=models.CharField(max_length=255, verbose_name='Modification type'),
        ),
        migrations.AlterField(
            model_name='usermanagementauditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modification date'),
        ),
        migrations.CreateModel(
            name='CountryAdminAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Modification date')),
                ('change_type', models.CharField(max_length=255, verbose_name='Modification type')),
                ('previous_entry', models.TextField()),
                ('new_entry', models.TextField()),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.TolaUser')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.Country')),
                ('disaggregation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.DisaggregationType')),
            ],
            bases=(models.Model, tola_management.models.DiffableLog),
        ),
    ]
