# Generated by Django 2.2.9 on 2020-06-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0010_add_countrylog_and_use_sentence_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRationaleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.BooleanField(default=False, verbose_name='Other')),
                ('adaptive_management', models.BooleanField(default=False, verbose_name='Adaptive management')),
                ('budget_realignment', models.BooleanField(default=False, verbose_name='Budget realignment')),
                ('changes_in_context', models.BooleanField(default=False, verbose_name='Changes in context')),
                ('costed_extension', models.BooleanField(default=False, verbose_name='Costed extension')),
                ('covid_19', models.BooleanField(default=False, verbose_name='COVID-19')),
                ('donor_requirement', models.BooleanField(default=False, verbose_name='Donor requirement')),
                ('implementation_delays', models.BooleanField(default=False, verbose_name='Implementation delays')),
            ],
        ),
        migrations.AddField(
            model_name='programauditlog',
            name='rationale_selections',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tola_management.AuditLogRationaleSelection'),
        ),
    ]
