# Generated by Django 2.2.9 on 2020-07-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0011_auto_20200616_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogrationaleselection',
            name='other',
            field=models.BooleanField(default=False, verbose_name='Other (please specify)'),
        ),
    ]
