# Generated by Django 3.2.12 on 2022-10-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0013_auto_20200928_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogrationaleselection',
            options={'verbose_name': 'Audit Log Rationale Selection', 'verbose_name_plural': 'Audit Log Rationale Selections'},
        ),
        migrations.AlterModelOptions(
            name='countryadminauditlog',
            options={'verbose_name': 'Country Admin Audit Log', 'verbose_name_plural': 'Country Admin Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='organizationadminauditlog',
            options={'verbose_name': 'Organization Admin Audit Log', 'verbose_name_plural': 'Organization Admin Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='programadminauditlog',
            options={'verbose_name': 'Program Admin Audit Log', 'verbose_name_plural': 'Program Admin Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='programauditlog',
            options={'verbose_name': 'Program Audit Log', 'verbose_name_plural': 'Program Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='usermanagementauditlog',
            options={'verbose_name': 'User Management Audit Log', 'verbose_name_plural': 'User Management Audit Logs'},
        ),
    ]
